DEFRA/aqie-front-end

src/config/index.js, src/config/nunjucks/context/build-navigation.js, src/config/nunjucks/context/build-navigation.test.js, src/config/nunjucks/context/index.js, src/index.js, src/server/index.js
This is currently still needed - we will pick up looking into this soon in the Platform team
=> Add app path prefix work back in

src/config/index.js, src/config/nunjucks/context/build-navigation.testbck.js, src/server/home/index.njk, src/server/index.js
fixing prefix temporally and remove unit test for navigation temporally.
=> fixing prefix temporally and remove unit test for navigation temporally.

src/config/index.js, src/config/nunjucks/context/build-navigation.test.js, src/server/home/controller.js, src/server/home/index.njk, src/server/index.js
created manual prefixes for routers.
=> created manual prefixes for routers.

src/server/common/components/includes/pollutants.njk, src/server/common/templates/layouts/page.njk, src/server/feedback/controller.js, src/server/feedback/index.js, src/server/feedback/index.njk, src/server/nitrogen-dioxide/controller.js, src/server/nitrogen-dioxide/index.js, src/server/nitrogen-dioxide/index.njk, src/server/ozone/controller.js, src/server/ozone/index.js, src/server/ozone/index.njk, src/server/particulate-matter-10/controller.js, src/server/particulate-matter-10/index.js, src/server/particulate-matter-10/index.njk, src/server/particulate-matter-25/controller.js, src/server/particulate-matter-25/index.js, src/server/particulate-matter-25/index.njk, src/server/router.js, src/server/search-location/controller.js, src/server/sulphur-dioxide/controller.js, src/server/sulphur-dioxide/index.js, src/server/sulphur-dioxide/index.njk
added pollutants pages and some unhappy paths pages.
=> added pollutants pages and some unhappy paths pages.

src/server/common/components/header/template.njk, src/server/common/templates/layouts/page.njk
=> fixed header hyperlink.

package-lock.json, package.json, src/server/home/controller.js, src/server/home/index.njk, src/server/search-location/index.njk
login error handling and fix library cookie bug.
=> login error handling and fix library cookie bug.

src/server/common/templates/layouts/page.njk, src/server/home/index.njk, src/server/search-location/index.njk
=> fixes to login page.

src/server/home/controller.js
fixing error link in login page.
=> fixing error link in login page.

src/server/data/air-quality.js, src/server/search-location/index.njk
=> Multiple bugs and updates 3

src/server/index.js, src/server/locations/controller.js
=> changed dotenv import.

src/server/common/templates/layouts/page.njk, src/server/search-location/index.njk
layout fixes and copy content.
=> layout fixes and copy content.

src/server/common/templates/partials/daqi-index.njk, src/server/common/templates/partials/pollutants.njk, src/server/locations/controller.js, src/server/nitrogen-dioxide/index.njk, src/server/ozone/index.njk, src/server/particulate-matter-10/index.njk, src/server/particulate-matter-25/index.njk, src/server/sulphur-dioxide/index.njk
updates for James copies and location title when not found.
=> updates for James copies and location title when not found.

src/server/common/templates/partials/daqi.njk, src/server/index.js, src/server/locations/helpers/fetch-data.js
clearing redis cache using client redis and fixing accessibility for ticket 440663
=> clearing redis cache using client redis and fixing accessibility for ticket 440663

src/server/data/en/en.js
=> typo fix in text.

src/server/nitrogen-dioxide/controller.test.js, src/server/nitrogen-dioxide/cy/controller.test.js, src/server/nitrogen-dioxide/cy/index.test.js, src/server/nitrogen-dioxide/index.test.js, src/server/ozone/controller.test.js, src/server/ozone/cy/controller.test.js, src/server/ozone/cy/index.test.js, src/server/ozone/index.test.js, src/server/particulate-matter-10/controller.test.js, src/server/particulate-matter-10/cy/controller.test.js, src/server/particulate-matter-10/cy/index.test.js, src/server/particulate-matter-10/index.test.js, src/server/particulate-matter-25/controller.test.js, src/server/particulate-matter-25/cy/controller.test.js, src/server/particulate-matter-25/cy/index.test.js, src/server/particulate-matter-25/index.test.js, src/server/sulphur-dioxide/controller.test.js, src/server/sulphur-dioxide/cy/controller.test.js, src/server/sulphur-dioxide/cy/index.test.js, src/server/sulphur-dioxide/index.test.js
Added unit test cases for pollutants
=> committing unit test cases for pollutants

src/server/common/templates/partials/pollutants.njk, src/server/cookies/cy/index.test.js, src/server/cookies/index.test.js, src/server/data/cy/cy.js, src/server/data/en/en.js, src/server/health/index.test.js, src/server/home/cy/index.test.js, src/server/home/index.test.js
Code change for ordering pollutants
Unit test cases for Cookies, home and health
=> AQC-49 for Ordering the Pollutants

jest.config.js, src/server/data/en/monitoring-sites.js, src/server/locations/location.njk
adding code change for ACQ-48 
updating jest config to ignore untested files to check the coverage
=> update the code for ACQ-48

src/server/locations/cy/controller.js, src/server/locations/cy/middleware-cy.js, src/server/locations/helpers/fetch-data.js, src/server/locations/helpers/middleware-helpers.js
fixed partial postcode for both en/cy and initial test for NI
=> fixed partial postcode for both en/cy and initial test for NI

src/server/common/templates/layouts/page.njk, src/server/locations/middleware.js
Northern ireland refactoring 5 with updates and fix for main page.njk
=> Northern ireland refactoring 5 with updates and fix for main page.njk

src/server/data/cy/cy.js
updated welsh content for start page
=> updated welsh content for AQC-104

src/server/data/cy/monitoring-sites.js
bug fix for pollutant ordering in table for welsh-AQC-207
=> bug fix for pollutant ordering in table for welsh-AQC-207

src/server/common/helpers/stringUtils.test.js, src/server/data/cy/cy.js, src/server/data/en/en.js, src/server/location-id/controller.js, src/server/location-id/cy/controller.js, src/server/locations/cy/controller.js, src/server/locations/cy/middleware-cy.js, src/server/locations/helpers/convert-first-letter-into-upper-case.js, src/server/locations/helpers/convert-first-letter-into-upper-case.test.js, src/server/locations/helpers/generate-daily-summary-with-calendar-day.js, src/server/locations/helpers/generate-daily-summary-with-calendar-day.test.js, src/server/locations/helpers/middleware-helpers.js, src/server/locations/helpers/show-location-page.js, src/server/locations/helpers/show-location-page.test.js, src/server/locations/helpers/uk-ni-select-util.js, src/server/locations/location.njk, src/server/locations/middleware.js, src/server/multiple-results/controller.js, src/server/multiple-results/cy/controller.js
- added code changes for "Air Quality in " in-front of location name
- Include forecast as 3 parts under "UK air pollution summary"
- Added test cases for utility files
=> Code changes for AQC-100 & AQC-90

src/server/data/en/en.js
updated typo for Sulphur dioxide description content
=> updated typo for Sulphur dioxide description content

src/server/location-id/controller.js, src/server/location-id/cy/controller.js, src/server/locations/cy/middleware-cy.js, src/server/locations/helpers/get-nearest-location.js, src/server/locations/helpers/middleware-helpers.js, src/server/locations/middleware.js
Clearing logs and 2 bugs 1-Typo with welsh English table "Level". Page not found for NI
=> fixed welsh/english table Level typo and NI not found page.

src/server/location-id/controller.js
=> check git tags

src/server/locations/helpers/fetch-data.js, src/server/locations/helpers/transform-summary-keys.js, src/server/locations/helpers/transform-summary-keys.test.js, src/server/locations/location.njk, src/server/multiple-results/multiple-locations.njk
fixed AQC-232 hide forecast summary for outdated data and AQC-234 populated place updated in multiple result page
=> fixed AQC-232 and AQC-234

src/server/multiple-results/multiple-locations.njk
reverting displaying populated place in multiple location result page
=> reverting displaying populated place in multiple location result page

src/server/location-id/controller.js, src/server/location-id/cy/controller.js, src/server/locations/helpers/middleware-helpers.js
fixed pollutants table location for multiple locations.
=> fixed pollutants table location for multiple locations.

db.json, src/config/index.js, src/server/error/index.njk, src/server/locations/cy/middleware-cy.js, src/server/locations/helpers/convert-string.js, src/server/locations/helpers/fetch-data.js, src/server/locations/helpers/get-postcode-type.js, src/server/locations/helpers/get-search-terms-from-url.js, src/server/locations/helpers/middleware-helpers.js, src/server/locations/middleware.js
Multiple fixes for bookmark page not found options
=> Aqc 238 243 240 bugs

src/server/common/templates/layouts/page.njk
added meta tag for google site verification
=> added meta tag for google site verification
